# include: package:flutter_lints/flutter.yaml
# linter:
#   rules:

include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
